#!/bin/bash

sonos=$(bar/commands/bin/sonos list-zones)

zone=$(echo $sonos | perl -wlne 'print $1 if /(.*:\d*)/')

current=$(bar/commands/bin/sonos current-track --zone=$zone)

title=$(echo $current | perl -wlne 'print $1 if /Title:(.*)Album/')
artist=$(echo $current | perl -wlne 'print $1 if /Artist:(.*)/')

echo $artist - $title

